/** @format */

import type { Metadata } from 'next'
import './globals.css'
import { AppProviders } from './AppProviders'
import { Manrope } from 'next/font/google'

const manrope = Manrope({
  subsets: ['latin'],
  weight: ['400', '600', '700'],
  variable: '--font-manrope' // optional: dùng biến CSS
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className="mdl-js">
      <body className={`text-(--text-title) antialiased`}>
        <AppProviders>{children}</AppProviders>
      </body>
    </html>
  )
}
